routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web', 'auth']], function () {
    /**
     * Route group for clients
     */
    Route::group(['namespace' => 'Client', 'prefix' => 'client'], function() {
        Route::get('recipe-ingredients/{id}/addingredient', 'RecipeIngredientController@addingredient')->name('client.recipe-ingredient.addingredient');
        Route::resource('recipes', 'RecipeController')->names('client.recipes');
        Route::resource('ingredients', 'IngredientController')->names('client.ingredients');
        Route::resource('recipe-ingredients', 'RecipeIngredientController')->names('client.recipe-ingredients');
    });
});

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Recipe
 * @package App\Models
 *
 * @property integer                 $id
 * @property integer                 $user_id
 * @property string                  $name
 * @property string                  $recipe
 * @property string                  $description
 * @property string                  $created_at
 * @property string                  $updated_at
 */
class Recipe extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'user_id', 'recipe', 'description',
    ];

    /**
     * recipeIngredients
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function recipeIngredients()
    {
        return $this->hasMany(RecipeIngredient::class, 'recipe_id', 'id');
    }
}

app/Http/Controllers/Client/IngredientController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\IngredientCreateRequest;
use App\Http\Requests\IngredientUpdateRequest;
use App\Models\Ingredient;
use App\Models\RecipeIngredient;
use App\Repositories\IngredientRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userId = auth()->user()->id;
        $items = app(IngredientRepository::class)->getMyWithPaginate($userId, 15);
        return view('_client.ingredient.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = app(Ingredient::class);
        $userId = auth()->user()->id;

        return view('_client.ingredient.create', compact('item', 'userId'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  IngredientCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(IngredientCreateRequest $request)
    {
        $data = $request->input();
        $item = (new Ingredient())->create($data);

        if ($item) {
            return redirect()
                ->route('client.ingredients.index')
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Ingredient::find($id);
        return view('_client.ingredient.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  IngredientUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(IngredientUpdateRequest $request, $id)
    {
        $item = Ingredient::find($id);
        if (empty($item) || auth()->user()->id != $item->user_id) {
            return back()
                ->withErrors(['msg' => "Ingredient id={$id} not found"])
                ->withInput();
        }
        $data = $request->input();

        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('client.ingredients.index')
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = false;
        $check = RecipeIngredient::where(['ingredient_id' => $id])->first();
        if (!$check) {
            $result = Ingredient::find($id)->delete();
        }

        if ($result) {
            return redirect()
                ->route('client.ingredients.index')
                ->with(['success' => 'Successfully deleted']);
        } else {
            return back()->withErrors(['msg' => 'Deleting was failed. Check this ingredient in yours recipes!']);
        }
    }
}

app/Http/Controllers/Client/RecipeController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\IngredientUpdateRequest;
use App\Http\Requests\RecipeCreateRequest;
use App\Http\Requests\RecipeUpdateRequest;
use App\Models\Recipe;
use App\Repositories\RecipeIngredientRepository;
use App\Repositories\RecipeRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userId = auth()->user()->id;
        $items = app(RecipeRepository::class)->getMyWithPaginate($userId, 10);
        return view('_client.recipe.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = app(Recipe::class);
        $userId = auth()->user()->id;

        return view('_client.recipe.create', compact('item', 'userId'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  RecipeCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RecipeCreateRequest $request)
    {
        $data = $request->input();
        $item = (new Recipe())->create($data);

        if ($item) {
            return redirect()
                ->route('client.recipes.show', $item->id)
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /**
         * @var Recipe $item
         */
        $item = Recipe::find($id);
        $recipeIngredients = app(RecipeIngredientRepository::class)->getAllWithPaginate($id, 20);
        return view('_client.recipe.show', compact('item','recipeIngredients'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Recipe::find($id);
        return view('_client.recipe.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  RecipeUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RecipeUpdateRequest $request, $id)
    {
        $item = Recipe::find($id);
        if (empty($item) || auth()->user()->id != $item->user_id) {
            return back()
                ->withErrors(['msg' => "Recipe id={$id} not found"])
                ->withInput();
        }
        $data = $request->input();

        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('client.recipes.index')
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = Recipe::find($id)->delete();

        if ($result) {
            return redirect()
                ->route('client.recipes.index')
                ->with(['success' => 'Successfully deleted']);
        } else {
            return back()->withErrors(['msg' => 'Deleting was failed.']);
        }
    }
}

app/Http/Controllers/Client/RecipeIngredientController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\RecipeIngredientCreateRequest;
use App\Http\Requests\RecipeIngredientUpdateRequest;
use App\Models\Ingredient;
use App\Models\RecipeIngredient;
use App\Repositories\IngredientRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RecipeIngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function addingredient($id)
    {
        $userId = auth()->user()->id;
        $item = app(RecipeIngredient::class);
        $ingredientList = app(IngredientRepository::class)->getAllForSelect($userId);

        return view('_client.recipe-ingredient.create', compact('item', 'id', 'ingredientList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  RecipeIngredientCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RecipeIngredientCreateRequest $request)
    {
        $data = $request->input();
        $item = (new RecipeIngredient())->create($data);

        if ($item) {
            return redirect()
                ->route('client.recipes.show', $item->recipe_id)
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = RecipeIngredient::find($id);
        $name = Ingredient::find($item->ingredient_id)->name;
        return view('_client.recipe-ingredient.edit', compact('item', 'name'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  RecipeIngredientUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RecipeIngredientUpdateRequest $request, $id)
    {
        $item = RecipeIngredient::find($id);
        if (empty($item)) {
            return back()
                ->withErrors(['msg' => "Ingredient id={$id} not found"])
                ->withInput();
        }
        $data = $request->input();

        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('client.recipes.show', $item->recipe_id)
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = RecipeIngredient::find($id);
        $result = $item->delete();

        if ($result) {
            return redirect()
                ->route('client.recipes.show', $item->recipe_id)
                ->with(['success' => 'Successfully deleted']);
        } else {
            return back()->withErrors(['msg' => 'Deleting was failed.']);
        }
    }
}

app/Http/Controllers/Guest/RecipeController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Models\Recipe;
use App\Repositories\RecipeIngredientRepository;
use App\Repositories\RecipeRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = app(RecipeRepository::class)->getAllWithPaginate(5);
        return view('_guest.recipe.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /**
         * @var Recipe $item
         */
        $item = Recipe::find($id);
        $recipeIngredients = app(RecipeIngredientRepository::class)->getAllWithPaginate($id, 20);
        return view('_guest.recipe.show', compact('item','recipeIngredients'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/_client/recipe/create.blade.php
@extends('layouts.app')

@section('content')
    @php
        /** @var \App\Models\Recipe $item */
    @endphp
    <div class="container">

        @include('_client.recipe.includes.result_messages')
        <form method="POST" action="{{ route('client.recipes.store') }}">

            @csrf
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">Create new recipe</div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="user_id" hidden></label>
                                        <input name="user_id"
                                               value="{{ $userId }}"
                                               id="user_id"
                                               type="number"
                                               class="form-control"
                                               hidden>
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input name="name"
                                               value="{{ old('name', $item->name) }}"
                                               id="name"
                                               type="text"
                                               class="form-control"
                                               minlength="3"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea name="description"
                                                  rows="10"
                                                  id="description"
                                                  class="form-control">{{ old('description', $item->description) }}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="recipe">Recipe</label>
                                        <textarea name="recipe"
                                                  rows="20"
                                                  id="recipe"
                                                  class="form-control">{{ old('recipe', $item->recipe) }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-3">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/_client/recipe/edit.blade.php
@extends('layouts.app')

@section('content')
    @php
        /** @var \App\Models\Recipe $item */
    @endphp
    <div class="container">

        @include('_client.recipe.includes.result_messages')
        <form method="POST" action="{{ route('client.recipes.update', $item->id) }}">
            @method('PATCH')

            @csrf
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">Edit</div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="id" hidden></label>
                                        <input name="id"
                                               value="{{ $item->id }}"
                                               id="id"
                                               type="number"
                                               class="form-control"
                                               hidden>
                                    </div>
                                    <div class="form-group">
                                        <label for="user_id" hidden></label>
                                        <input name="user_id"
                                               value="{{ $item->user_id }}"
                                               id="user_id"
                                               type="number"
                                               class="form-control"
                                               hidden>
                                    </div>
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input name="name"
                                               value="{{ old('name', $item->name) }}"
                                               id="name"
                                               type="text"
                                               class="form-control"
                                               minlength="3"
                                               required>
                                    </div>
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea name="description"
                                                  rows="10"
                                                  id="description"
                                                  class="form-control">{{ old('description', $item->description) }}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="recipe">Recipe</label>
                                        <textarea name="recipe"
                                                  rows="20"
                                                  id="recipe"
                                                  class="form-control">{{ old('recipe', $item->recipe) }}</textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-3">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/_client/recipe/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @include('_client.recipe.includes.result_messages')
        <div class="row justify-content-center">

            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-primary ml-auto" href="{{ route('client.recipes.create') }}">Add Recipe</a>
                </nav>
                <div class="card">
                    <div class="card-header">My Recipes</div>
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Recipe</th>
                                <th><pre>Description</pre></th>
                                <th>Ingredients</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($items as $item)
                                @php /** @var \App\Models\Recipe $item */ @endphp
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td><a href="{{ route('client.recipes.show', $item->id) }}">{{ $item->name }}</a></td>
                                    <td><pre>{{ $item->description }}</pre></td>
                                    <td class="img-thumbnail bg-info ml-auto">{{ $item->recipe_ingredients_count }}</td>
                                    <td class="text-right">
                                        <form class="d-inline" method="get" action="{{ route('client.recipes.edit', $item->id) }}">
                                            <button type="submit" class="btn btn-link"><img src="/images/icon-edit.png" alt="Delete"  height="15" width="15"></button>
                                        </form>
                                        <form class="d-inline" method="post" action="{{ route('client.recipes.destroy', $item->id) }}">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-link"><img src="/images/icon-trash.png" alt="Delete"  height="15" width="15"></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @if($items->total() > $items->count())
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                {{ $items->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/_client/recipe/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @php /** @var \App\Models\Recipe $item */ @endphp
            <div class="col-md-8">
                <div class="row justify-content-center">
                    <div class="card">
                        <div class="card-body">
                            <div class="mb-2">
                                {{ $item->name }}
                            </div>
                            <div class="mb-2">
                                {{ $item->description }}
                            </div>
                            <div class="mb-2">
                                {{ $item->recipe }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-md-8">
                @include('_client.recipe.includes.ingredients')
            </div>
        </div>

    </div>
@endsection