routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web', 'auth']], function () {
    /**
     * Route group for clients
     */
    Route::group(['namespace' => 'Client', 'prefix' => 'client'], function() {
        Route::get('recipe-ingredients/{id}/addingredient', 'RecipeIngredientController@addingredient')->name('client.recipe-ingredient.addingredient');
        Route::resource('recipes', 'RecipeController')->names('client.recipes');
        Route::resource('ingredients', 'IngredientController')->names('client.ingredients');
        Route::resource('recipe-ingredients', 'RecipeIngredientController')->names('client.recipe-ingredients');
    });
});

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Recipe
 * @package App\Models
 *
 * @property integer                 $id
 * @property integer                 $user_id
 * @property string                  $name
 * @property string                  $recipe
 * @property string                  $description
 * @property string                  $created_at
 * @property string                  $updated_at
 */
class Recipe extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'user_id', 'recipe', 'description',
    ];

    /**
     * recipeIngredients
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function recipeIngredients()
    {
        return $this->hasMany(RecipeIngredient::class, 'recipe_id', 'id');
    }
}

app/Http/Controllers/Client/RecipeController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Requests\IngredientUpdateRequest;
use App\Http\Requests\RecipeCreateRequest;
use App\Http\Requests\RecipeUpdateRequest;
use App\Models\Recipe;
use App\Repositories\RecipeIngredientRepository;
use App\Repositories\RecipeRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userId = auth()->user()->id;
        $items = app(RecipeRepository::class)->getMyWithPaginate($userId, 10);
        return view('_client.recipe.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = app(Recipe::class);
        $userId = auth()->user()->id;

        return view('_client.recipe.create', compact('item', 'userId'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  RecipeCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RecipeCreateRequest $request)
    {
        $data = $request->input();
        $item = (new Recipe())->create($data);

        if ($item) {
            return redirect()
                ->route('client.recipes.show', $item->id)
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /**
         * @var Recipe $item
         */
        $item = Recipe::find($id);
        $recipeIngredients = app(RecipeIngredientRepository::class)->getAllWithPaginate($id, 20);
        return view('_client.recipe.show', compact('item','recipeIngredients'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Recipe::find($id);
        return view('_client.recipe.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  RecipeUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RecipeUpdateRequest $request, $id)
    {
        $item = Recipe::find($id);
        if (empty($item) || auth()->user()->id != $item->user_id) {
            return back()
                ->withErrors(['msg' => "Recipe id={$id} not found"])
                ->withInput();
        }
        $data = $request->input();

        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('client.recipes.index')
                ->with(['success' => 'Successfully saved']);
        } else {
            return back()
                ->withErrors(['msg' => 'Saving was failed'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = Recipe::find($id)->delete();

        if ($result) {
            return redirect()
                ->route('client.recipes.index')
                ->with(['success' => 'Successfully deleted']);
        } else {
            return back()->withErrors(['msg' => 'Deleting was failed.']);
        }
    }
}

app/Http/Controllers/Guest/RecipeController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Models\Recipe;
use App\Repositories\RecipeIngredientRepository;
use App\Repositories\RecipeRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = app(RecipeRepository::class)->getAllWithPaginate(5);
        return view('_guest.recipe.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        /**
         * @var Recipe $item
         */
        $item = Recipe::find($id);
        $recipeIngredients = app(RecipeIngredientRepository::class)->getAllWithPaginate($id, 20);
        return view('_guest.recipe.show', compact('item','recipeIngredients'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/_client/recipe/includes/ingredients.blade.php
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Ingredients</div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Ingredient</th>
                        <th>Weight</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($recipeIngredients as $recipeIngredient)
                    @php /** @var \App\Models\RecipeIngredient $recipeIngredient */ @endphp
                    <tr>
                        <td>{{ $recipeIngredient->id }}</td>
                        <td><a href="{{ route('client.recipe-ingredients.edit', $recipeIngredient->id) }}">{{ $recipeIngredient->ingredients->name }}</a></td>
                        <td>{{ $recipeIngredient->weight }}</td>
                        <td>
                            <form method="post" action="{{ route('client.recipe-ingredients.destroy', $recipeIngredient->id) }}">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-link"><img src="/images/icon-trash.png" alt="Delete"  height="15" width="15"></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                <a class="btn btn-primary" href="{{ route('client.recipe-ingredient.addingredient', $item->id) }}">Add Ingredient</a>
                <a class="btn btn-primary" href="{{ route('client.ingredients.create') }}">Create Ingredient</a>
            </div>
        </div>
    </div>
</div>

@if($recipeIngredients->total() > $recipeIngredients->count())
    <br>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {{ $recipeIngredients->links() }}
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/_client/recipe/includes/result_messages.blade.php
@php /** @var \Illuminate\Support\ViewErrorBag $errors */ @endphp
@if($errors->any())
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <ul>
                    @foreach($errors->all as $errorTxt)
                        <li>{{ $errorTxt }}</li>
                    @endforeach
                </ul>
                {{ $errors->first() }}
            </div>
        </div>
    </div>
@endif

@if(session('success'))
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                {{ session()->get('success') }}
            </div>
        </div>
    </div>
@endif